version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdfasdf
      POSTGRES_DB: etek
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/home/k4r7ik/Projects/VulnTracker/Backend/db/data

volumes:
  postgres_data:
